In [1]:
import torch
import torch.nn as nn
import numpy as np
import argparse
import torch_gnn.utils
import torch_gnn.dataloader
from torch_gnn.gnn_wrapper import GNNWrapper, SemiSupGNNWrapper
import matplotlib.pyplot as plt
import networkx as nx
import json
from tqdm import tqdm
import pandas as pd

In [2]:
df_test = pd.read_csv('../data/test.csv')
print(df_test.shape)

(43560, 3)


In [4]:
def convert_string_to_tensor(string):
    return string.replace('[', '').replace(']', '').replace(' ', '').split(',')

def get_x(vectors):
    x = np.zeros((len(vectors), 201))
    for i,vector in tqdm(enumerate(vectors)):
        #print(int(vector))
        x[i,0] = int(vector)
        x[i,1:] = np.array(convert_string_to_tensor(vectors[vector]['vector']))
        #x.append(convert_string_to_tensor(vectors[vector]['vector']))
        #x[-1].append(int(vector))
        #print(x)
        #break
    return np.array(x, dtype=np.float32)

In [6]:
with open("../data/Vectors_and_clusters.json") as file:
    vectors = json.load(file)

x = get_x(vectors)
print(x.shape)
print(x[:10])

624181it [01:06, 9391.27it/s] 


(624181, 201)
[[ 3.6030000e+03  2.0776278e-01  3.1964138e-01 ...  9.5893174e-02
   7.7129021e-02 -9.0744056e-02]
 [ 7.3830000e+03  2.6104581e-01  1.2609364e-01 ...  1.9141915e-01
  -4.4091266e-02 -3.9251558e-03]
 [ 1.4309000e+04  2.3514135e-01  2.4830784e-01 ...  4.2272650e-02
   1.6477853e-01 -8.3062634e-02]
 ...
 [ 4.9226000e+04  1.6412792e-01  2.6631457e-01 ...  1.0477072e-02
   4.1543197e-02 -5.5518728e-02]
 [ 4.9575000e+04  3.2011482e-01  2.2751243e-01 ...  1.1337683e-01
  -5.6078650e-02 -4.3000844e-03]
 [ 5.4153000e+04  6.0976766e-02  2.9971105e-01 ...  8.6528830e-02
   1.7097486e-02  5.7324026e-02]]


In [20]:
num = x[:,0].astype(int)
vec = x[:,1:]
print(num)
print(vec)

[      3603       7383      14309 ... 2908480256 2908495104 2908510976]
[[ 0.20776278  0.31964138  0.13893002 ...  0.09589317  0.07712902
  -0.09074406]
 [ 0.2610458   0.12609364  0.10306707 ...  0.19141915 -0.04409127
  -0.00392516]
 [ 0.23514135  0.24830784  0.26340294 ...  0.04227265  0.16477853
  -0.08306263]
 ...
 [ 0.24471392  0.1022459   0.03518641 ...  0.00597861 -0.05725859
  -0.02161019]
 [ 0.16219223  0.1659188   0.14239211 ... -0.02363729 -0.08755589
  -0.02170765]
 [ 0.20999359  0.08475576  0.10483249 ... -0.0883003  -0.11674631
  -0.03362756]]


In [13]:
# load the graph
G = nx.read_edgelist('../data/coauthorship.edgelist', delimiter=' ', nodetype=int)

In [14]:
edges = np.array(list(G.edges))
E = np.zeros((edges.shape[0], 3), dtype=int)
E[:,:-1] = edges
print(E[:10])

[[2002218453 1999212242          0]
 [2002218453 2032640503          0]
 [2002218453 2475931411          0]
 [2002218453 2477743428          0]
 [2002218453 2504846374          0]
 [2002218453 2597456557          0]
 [2002218453 2598017501          0]
 [2002218453 2134271654          0]
 [2002218453 2138551865          0]
 [2002218453 2145694960          0]]


In [16]:
nodes = np.array(list(G.nodes))
n = len(nodes)
print(nodes[:10])
"""for i in tqdm(range(n)):
    E = np.where(E==nodes[i], i, E)
print(E[:10])
"""

[2002218453 1999212242 2032640503 2475931411 2477743428 2504846374
 2597456557 2598017501 2134271654 2138551865]


'for i in tqdm(range(n)):\n    E = np.where(E==nodes[i], i, E)\nprint(E[:10])\n'

In [9]:
np.save('../data/E.npy', E)

In [17]:
F = np.load('../data/E.npy')
print(F.shape)

(1718164, 3)


In [21]:
print(num.shape)
print(nodes.shape)
print(vec.shape)

(624181,)
(217801,)
(624181, 200)


In [22]:
print(num[:10]) # papers
print(nodes[:10]) # authors

[ 3603  7383 14309 15548 15883 43287 43295 49226 49575 54153]
[2002218453 1999212242 2032640503 2475931411 2477743428 2504846374
 2597456557 2598017501 2134271654 2138551865]


In [30]:
#N = np.zeros((nodes.shape[0], vec.shape[1]+1))
#for i in range(n):
#    N[i,:-1] = vec[num==nodes[i]]

In [73]:
# Add features to nodes, for now with only the first paper
from numpy import genfromtxt

data = genfromtxt('../data/author_papers.txt', delimiter=':', dtype=str)
"""with open('../data/author_papers.txt', 'rb') as f:
    clean_lines = (line.replace(b':',b'-') for line in f)
    data = np.genfromtxt(clean_lines, dtype=int, delimiter='-')"""
print(data[:10])
N = np.zeros((nodes.shape[0], vec.shape[1]+1))
#print(np.min(num))
for i in tqdm(range(n)):
    author = int(data[i,0])
    papers = np.array(data[i,1].split('-'), dtype=int)
    print(papers)
    if np.sum(np.array([num==paper for paper in papers])) == 0:
        continue
    print(i)
    p = -1
    for j in range(len(papers)):
        if np.sum(num==papers[j]) == 1:
            p = j
            break
    N[nodes==author,:-1] = vec[np.argmax(num==papers[p])] # choice: 1st article
    #print(i, N[nodes==author,:])

np.save('../data/N.npy', N)

[['1036332' '1510273386-1827736641-1588673897-2252711322-2123653597']
 ['1101850' '133459021-179719743-2111787673-2126488676-31838995']
 ['1336878' '2122092249-2132109814-2100271871-2065672539-2036413831']
 ['1515524' '2141827797-2127085795-2013547785-2138529788-1994863898']
 ['1606427' '1907724546']
 ['2728936' '2114261446-2042751882-1912205781-2059913822-1905787154']
 ['3720290' '2034815413-1943970375']
 ['4265922' '2158924658-1974358662-2171008951-2143116731-2098197194']
 ['4631324' '971425015-1005190365-2775011729-1498234799-2724553065']
 ['4652436' '2029513180-1578614537-2081547332-2464290036-2164356097']]


  0%|          | 14/217801 [00:00<26:03, 139.33it/s]

[1510273386 1827736641 1588673897 2252711322 2123653597]
[ 133459021  179719743 2111787673 2126488676   31838995]
[2122092249 2132109814 2100271871 2065672539 2036413831]
[2141827797 2127085795 2013547785 2138529788 1994863898]
[1907724546]
[2114261446 2042751882 1912205781 2059913822 1905787154]
[2034815413 1943970375]
[2158924658 1974358662 2171008951 2143116731 2098197194]
[ 971425015 1005190365 2775011729 1498234799 2724553065]
[2029513180 1578614537 2081547332 2464290036 2164356097]
[2105079611 1992208760 2279367517 2426248896 2621319086]
[2114019248 2093052046 2028390205 1964770860 1992919395]
[2107960133 2396074414 2129324673 2129413054 2102857011]
[1816889752 2121942750 2022175747 2160727671 2056356307]
[1502855729 1986976921 2033310317 1482478137 2070163745]
[2113072427 2118676866 1571134607 1533950051 2108893718]
[2250322698 1998727264 2534937603 2362118473 1973707044]
[2012580531 2101108259 2060346657 2502258425 2152204876]
[1991858502 1998285060 2017661493 2022175859 211891

  0%|          | 42/217801 [00:00<27:44, 130.81it/s]

[2043509228 2074682587 1516646538 2073324778 1991213319]
[2099117796 1775249800 2163356528 2163356528 2136926356]
[2042903050 2345834824 1523757897 2529231049 1537393433]
[2061496053 2009357736 2017052870 2101668373 1979357511]
[1916347105 2200417596 1602822231 1845319420 2278091522]
[2145929661 2159740793 1970935025 2127899917 2146434055]
[1861904931 1532705157 2002713980 2034120147 2165763959]
[2114332313  413048612 2078181413 2018191967   56964303]
[2574017551 2514974017 2091939272 1519699895 2005886648]
[2166743687 1996836135 2021228972 1543770286 2102874665]
[2034794977 2027310126 2141925722 2443352794 2067384246]
[1981663600 1553781048 1541262581 1559076720   39416990]
[2519880423 2120474977  247037805 2621222911  311257967]
[2168884369 1482261514 2132934597 1791702618 2146288980]
[2151417693 2121325957 2129780509 1601355778 1563722977]
[2127113848 2110503030 2156467326 2130602336 2111748568]
[1673461548]
[2120119918 2111760412 1985654543 2110197150 1513257410]
[2137223451 196442

  0%|          | 69/217801 [00:00<30:35, 118.61it/s]

[2010099233 2000061529 2088390434 2091223968 2034846070]
[2100235918 2096945460 2123127356 2118023920 2170555940]
[2149236697 2293033107   23323356]
[2076899833 2084495494 2005307131 2047693594 1968476891]
[2036097053 1978527132 2164353258 1589064086 1982025738]
[2124289460   10089010 2191435020 1511906506  203432916]
57
[2005970478 2011846767 2075730198  224501458 1503748341]
[2008066109 2099881084 2155781791 2091485989 2155667629]
[2071060085 2075500923    9278068  101830517 2157238806]
60
[2044614976  132574275  148381804 2489425028]
[2081316069 2277934293]
[2086036443 2093188697 2045793256 1983313242 2487110705]
[2096606735 2744769540 2736607803 1521502542 1802013674]
[1488229309 2102196588 2168460490 2158242013 2018578825]
[1550071148 2141970373 1583268303  292077872  865824876]
[1680889589 2296146451 1988501112 2511569769 2498343511]
[2079245976 1803419465 1992581384 2765500576   61153243]
[1973860563 2025571615 2477622649 1998712523 2113820363]
[2128226234 2050706870 2168130050 

  0%|          | 95/217801 [00:00<29:40, 122.29it/s]

[1502496407 2270771286   11929522 2478392834 1825446528]
76
[2120135834 2084469887 2126839357 2166268240 1612645646]
[2210845408 2109380953 1638444543 2107373214 1035830498]
[2014629162 2027444023 2468078839 2565424434 2077215389]
[2091240930 1980550545 1561404291 2091711296 2735679777]
[2147762963 2089143594 1541545136 2576824898 2105461264]
[2039376592 2132891289 2125892920 1501480210 2171322294]
[1886448835 1488518937 2279466072 1514842408 1549179665]
[2124063321 2139877477 2125885386 2110896825 2010663007]
[2111195923 2085823706 1493451670 1593053027 1483018917]
[2090785509 2073165288 2075043143 2088403135 1532523962]
[2086631206 1429964360 2336291507 2151152024 2093213895]
[2068240988 2555053211  156746702 2118820512 2153339204]
[1997161938 2144710514 2023736093 1979532929 1974991592]
[1760205449 1966379407 2087843564   26655238 2111542911]
90
[1597931764 1503691113 1601524763 2145700552    8100481]
[2133751148   90209331  181751373 2107426594 2125022885]
[2152262131 2541775796 19

  0%|          | 121/217801 [00:00<29:12, 124.22it/s]

[2145494108  206655239 1517808374 2150772522 2113362355]
[2604968291 1759418197 2088657502 2289095019 2439507348]
[1973226301 2026944947 2069239002 1560903000 1887853655]
[2127474646 1564883604 1721621563 2041762692 2096329292]
[2087483562 2166881126 2535836978 2217233179 2025232178]
[2143821614 2098417235 2126302041 2155105016 2098012844]
[1971518725 2149877754 2163857507 2014763157 1982600306]
[2523989131 2523989131 2073380432 1979724564 2258396074]
[2060584735  243526469]
[1498484072 1977231480 2010039191   70117053   46044049]
[2219836174 1995997581 2105854671 2057860022 2064054177]
[2048720193 2056359839 2023923751 2046252907 2018224499]
[2144258433 2153613893 2160426410 1982309045 2082425789]
[2767914218 1986088036 2169599226 2067520428 1779441601]
[2120664464 2158670827 2087362566 1977804560 2076598610]
[2125681805 2000221080 2137488269  185597466 2163357786]
[2002325351 2026457735 2026590932 2144355623 1987235268]
[1602672367 2092198121 2092245922 2092245922 2041838121]
[208264

  0%|          | 149/217801 [00:01<28:05, 129.15it/s]

[1964524096 2162007818 1971362221 2565088041 2092549804]
[2137321308 1490019423 2134801216 2101942831 2096912425]
[1495226832 1948370231  200404955   89128506]
[2119173129 2091211860 2527435056 2117210319 2216521503]
[2001658408 2013682957 2123137684 1997742838 2086657055]
[1564102710 1825715633 2491758376 2110138773 2505241474]
[1603200341 2062248396 2165237418 2007800003 2133948129]
[2469357635 2515519694 2521695847 2521361431 1981520332]
[2100498403 2150454959 2139968447 1803719049 2063104454]
[2479704517 2069382570 2616341659 1518928998 1521360481]
[2053011040 1985074247 1570196665 2106036226 1530394198]
[2101904880 1983442906 2051799703 2019314734 2002112740]
[2115683289  218261244 2097658645  959280551 2075683427]
[2113112851 2158171113 1964013848 1518864151 1514547532]
[1982485071 2002480791   72428710 2108099373 2049055139]
[1588647531   39323315  195166290  152053113 2052306364]
[2075480071 1985324716 2405298789 2622946746 1952042740]
[2135669167 2118020774 2625146634 27414759

  0%|          | 181/217801 [00:01<25:37, 141.54it/s]

[2006478220 2159247414 2115808056 2132768042  137412864]
[2105634619 2116689128 1601201751 2003464575 2143633031]
[ 898942148 2108115817  643322139 2130202874 1578425718]
[1765055128 2039431054 2055301497 2302147823 2127321153]
[2033158821 2010362967 2026338207 2094888888 2130727935]
[1551114844 2042167027 2517252232 2025414846 1497399501]
[2136232495 2215173806 2111047576 1985587638 2059413159]
[1989314635 2158932032 2017360628 1990441952 2075127216]
[1967583234 1728303734 2003444513  142212369 2114627486]
[2148128686 2072513839 1880289998 1977124929 2141735882]
[1500085611 2122735631 1575079504 1516304047 1485718948]
[2113227443 2069002575 1970210633 1995609428 1040189461]
[ 127011120 2401553213 1597839571 2166481862 1487393892]
167
[2002857471 1877555071 1972585778   92424514  953414564]
[2117834610 2148523407 2168781359 1559496097 2142152445]
[2135269154 1997121481 2044986361 2186330282 1955741794]
[1586897116]
[2116405617 2755807592 2569552178  819047579 2602773008]
[2169607583 20

  0%|          | 210/217801 [00:01<27:18, 132.81it/s]

[1590360882 1512562726 1990589632 2048101063 1533863182]
[ 125134673 1968893782 1578462055 1530881258 2499456063]
[2167727518 2151512268 2130455390 2050654437 2105496423]
[  45950098 2167617363]
[2140313762 2140523882 2116790080 2067494918  149290654]
[2110907739 2130807793 2157829776   91429005 2164834626]
[2085629252 2133467832  182809541 2081616790 1994588422]
[1989936702 2107965664 2140321790 2158094026 1530950001]
[2143284875 1557943741 1565842579 2041902183 2148969593]
[1998096071 2095079964 2063368851 2032811211 2074076165]
[1538622809 2150497272 2138939456 1988869884 1492315901]
[2096568537 2154796257 2126516062 2138482845 2037212977]
[1983354426 1976388576 2021635355 2143835111 2035746958]
[2142357327 2110222233 2169696250 2171043104 2109118662]
[1523635368 2408078766 2306514557 2253399331  253777839]
[1899943246 2172206967  159999129 2064076961 2119653092]
[1987809485 2076981114  114162218 2064015040  202236097]
[1930427042  181583665 2156929189 2053914793 2140709543]
[215882

  0%|          | 224/217801 [00:01<28:26, 127.51it/s]

[1994213219 2010488831  110873351 2108278316 2072513255]
[2141959747 2161082594 2051676537 1819920475 2494546705]
[2141081078 2556810531 2345396352 2175456839 2082891426]
[2168909179 2004125187 1991056282 2166699767 2028133290]
[1975063206 1566443347 2144009807 2075096900 2102718280]
[ 133357243 2724665864 2748440410 2053348718 2067422488]
[2118026896 2052748973 2089662944  148068669 1969278886]
[2103029213 2097136062 2156382871 1999456664 1545098723]
[2095894588 2138547938 2102102439 1987873989 2117610793]
[2083016385 1895727713 2051228755 2003415090 1550938348]
[2122035503 2758705351 2601449720 2620868585  173080134]
[1495444061 1785797725 2580339477 2267469130 2538848838]
[ 126293500 1995494367 1875650419  183028343 1510258819]
[2140658777 2170113430 2129666444 2151216147 1970001805]
[1990485541 2022559449 2068944599 2168052482 2068537547]
[2168729696 2154734566 1995446935 2049882268 2009052798]
[2128737032 2105810688 2002312366 2148698873 1554598581]
227
[1582796148 1599783496 2106

  0%|          | 251/217801 [00:01<27:52, 130.04it/s]

[1552926662 2040368499 1553374920 1556837901 1547917072]
[2113319082 1983957744   50805047 2159233742 2151962787]
[2124736688 1919395891 2172097227 2143831726 2055665491]
[2465979459 2174991983  612325294 1920764510 2505144057]
[2140720561 2075667409 2070698019 2246821210 2037844134]
[2030729543  278235758 2069700160 2109525584 2129697331]
[ 203408848 2078245460 2109182845 2620390745 2165147737]
242
[2003977229 2025585452 2074513007  264463369 2318119323]
[2031411490 2065325623 2131934786  402432628 2161713768]
[1987061561 2048037629 1969261669   33987047 2113680484]
[1607732343 2155522880 2052129716 2133755482]
[2077379886 1999517458 2064823094 1494129366 2734576500]
[2086088774 2109866059 2070531512 1569502399 1994332955]
[2141423292 2159238794 2148659804 2162314411 2091664437]
[1588000771 1571045421  161315898 1993629555 2035463604]
[2007106955 1568405722 2041170865 1524457277 2118946173]
[  70674440 2239231358 2010052797 1916694713 2020458978]
252
[2056370875 2135065661 2136035751 

  0%|          | 280/217801 [00:02<27:08, 133.60it/s]

[2094567668 2083206550 2108322535 2005689470 2170541075]
[2121981798 2278679256  154504758 2248415505 2095871591]
[2172061120   52625589  195532427  146654746]
[1579218062 2165532165 1548986960 1848531833 2098320696]
[2107609298 2159142527 1980449090 2137645208 2090495398]
[2103699027 2087884525   69084629 2111953967 2042330180]
[2802410568 1507921835 2115546132  201872632  193144238]
[1909235296 1574497486 1503258163 2300089411 1004712286]
[2112130467 2097271989 2343238565 2114459720 2141853020]
[1988361254 2181256817 2159028135 2053930157 2568944034]
[2162566219 2505299260 2003764924 1574236237 1979003363]
[1754668934 2143081707  162242209 2182766230 2270361436]
[2110682677 2070048373 1546390227 1892054847 2267636275]
[2041391993 2050477758 2104196718 1542553173 2109305533]
[1503748341 2067256139 2103222411 1938890497   68460362]
[2053690446 2098548358]
[2765180549 1922401496 2047969825 2047969825 2098758347]
[2594255081 1593654652  793037554 2079574109 2074998972]
[2113346546 212740

  0%|          | 308/217801 [00:02<27:54, 129.85it/s]

[2004783820 2024528507 1990430898 1261199295 2122025954]
[2015280671 2021418918 2169673105 2032602169 2120735680]
[2157917411 2157917411 2124199755 2124199755 2162447676]
[1932046447 2156566552 1970009917 1594895242 1912439100]
[2539317369 2131694418 1545590170  165608072 1587808007]
[2047510114 2009399375 2075292177 1983050605 1624677845]
[2111174568 2076921701 2076921701 2058149529 2126737396]
[1992928849 2113426200 2165859533 2037818628    9278983]
296
[1547209727 2115931016 2008822987 2505555988 1509130113]
[2031188261 2042987983 1508602846 2113811859 1591094652]
[2042879619 1982430640 1509857015 2250325114  801764671]
[1555345174 1597993058 2121947632 2258706420 1518201759]
[2065415824 2146744591 2484001575 2093255724   50017966]
[2160335114 2140141066 2088328344 2108287924 2180485443]
[2057150268 2063155154 2124558608 2110761978 2300198213]
[2109184569 1864461701 2102455520 2093712250 1593557340]
[ 119255677 2107475457 1590074943 1687268979 2177768973]
[1973023914 2604853461 2499

  0%|          | 335/217801 [00:02<29:07, 124.44it/s]

[ 213769128 2799394054 2755541413  242160921 1503945574]
[2139480232 1483850525 2074662725 1537006541 1560719346]
[2202692359 2398495646 1522583870 1480394758 2407728550]
[2102802363 2107284210 2169327824 1808782381  109245773]
[1982660193  159012016 2074103318 2078533235 2114257725]
320
[1553052391 1971320885 2151430568 1484729457 2168599422]
[1988215135 2559356241 2341665358 2151003383]
[2156798505 2046192291 2134299061 2106116715 2152064613]
[1973822881 2078825564 2067829452 2146693432 2279283933]
[2046326907  314843828 1998400278 2124594848 1995418292]
[2028933639 1966770690 2467817718 2122553496 2158126296]
[2153595771 2119600007 2396881363 2107949418 2160987310]
[  63896271 2151841521 2007019539    8970143 2098031622]
328
[2154768509 1767678477 2133986470 2102239128 2394961746]
[2027527947 2119119741  175652216 2107506775 1608556992]
[2117958809 1600320111 1916670372 1548071467 2265984730]
[2140315169 2126758253 2051173773    5191425  223358010]
332
[2148698435 2130362098 2026062

  0%|          | 363/217801 [00:02<28:08, 128.80it/s]

[2125942035 2599054632 1541384020 2465477906 1567414150]
[2125580772 1520369706 2098921651 1888219919 2090815861]
[1548957255 2154546957 1571803258    6867492 2165377793]
341
[1892798954 2612279584 2572799557 1528076390 2113085788]
[1512329411 1969311876 1772407568 2002587184 2268502312]
[131489028  51109484 163605401]
[2131747693 2007661494 1541618397]
[2139247256 2053445022 2068162320 2144311271 2064141177]
[2172426415 1658990193 1528817773 2165949021]
[1800526726 2624106077 2177114966 1601250469 2606296640]
[2232993910 1978277148 2734379643 1990373437 2512912828]
[2125555950 2096059127 2123296410 2161566505 2106710314]
[2139738526  183110888 2118029092 2325765875 2136401731]
[1997246149 2290807635 2169812457 2159309554 1573952599]
[1506512961 2125942035  155249106 2587099127 1980185135]
[  80104197 2085736663 1486342128 2102547224 2485732118]
[2137789046 2104692902 1737058272 2156732358 2068701608]
[2162071525 2127282414 2080883604 2069801930 1997470865]
[1495083464 1836078613 21387

  0%|          | 391/217801 [00:03<27:29, 131.77it/s]

[2087677309 2124603636 2142636026 2145767879 1934807066]
[1607229125 2151349330 1489491826 2132416301 2616407667]
[2429942626 2043218103 2029625486 2020086177 1990488220]
[2130264930 1974388055 2122048894 2094611631 1893382533]
[2108797218 1482374180 2532893037 2291554282 1546703885]
[2003882881 2162048586 1999574790 2346474620 2059162423]
[2070797217 2017822598 2068956920 1570567637 2739967600]
[1657354101 2108241838 2169309022 1974133806 2084845478]
[2060067830 2057679339 2025573206 2066009691 1977842749]
[1489726511 1995478677 1520053934  124275116 2164000438]
[1979638981 1593453304 1490283603 1972281109 2072635123]
[1590013720 2020741690 2225853121 1972027011 1565296018]
[2792304136 2084542938 1508697289 1970926733 2077739389]
[2153991022 2342256133 2128205319 2169303607 2137212179]
[2109104929 2038531095 2131152435 2094767863 1990453879]
[2145747124 1486723877 2097597750 1771592512 2032596397]
[1547691662 1532221428 1877037102 1559058868 1951939261]
[2027471022 2006453614   449364

  0%|          | 422/217801 [00:03<25:35, 141.59it/s]

[2720019074 2008758790 2504993077 1509997393 2284614837]
[2006546956 2115060445 1784642696 2312691598 2543951368]
[2160842479 2735986417 2078139657 2098053810 2096972221]
[2104246989 2160221625 1612011551 2031723180  198545313]
[2020080115 2095926699 1990265015 2896418411 2049390374]
[1990370351 2177357765 2062792908 1561777167 1501258188]
[2125595978 2062184799 2019471084 2105943854 1977727639]
[ 124685440   20690315 2402461178 2031342629  178350596]
401
[2105714739 1866429870 2137199598 2247862869 2133314934]
[1729367871  137374081 2010670781 2158650228   72460630]
[2105807304 2185751161 2082302382 2021350343 2164441647]
[2038010270 2142352693 2103267130 2150936750 2164637175]
[1974008324   10358444 2271328583 2132375778 1568182574]
406
[1509485343   82035802 1548031742 1871900403 1537861563]
[2124949029 2224545258 2133987928 2263250858 1793622813]
[1579614261  159269753  121633690 2338501177  108989321]
[2102240299 1524150562 1988320382 2125442437 2131550499]
[1674150949 2164223141 

  0%|          | 452/217801 [00:03<25:54, 139.80it/s]

[2111473977 2089544541 2106135602 1979929531 2101546667]
[1975037309 1589004867 2600443660]
[2153204881 2149129030 1965430787 1603884835 2120331424]
[2063905556 1857949261 1507832814   98280286 1488731993]
[2128181433 2125032792 2098930385 2149449925 1574986862]
[2083112818 2004197977 1815403589 2015281880  101712127]
[2052361825   71268747 1829112739 2098903611 1545466437]
[2279561648  111436885  310143269]
[2115801316 1855576760 2159422401 2159422401 2161998322]
[1987952743 2082380454 1547905826 1976744991  126051208]
[1972440514 1496208045   39079713 2495137914  156656192]
436
[  86739652 1552824673 2156678043  233688501  122328141]
[2098970373 2057585911 2049037263 2014119048 2071865101]
[1979636842 1540016664 2073051573 1516817778 2006651430]
[1522769603 1507516664 2100588330 2172794850 1503212595]
[2077986488 2124758336 2016051764 2018360901 2057380059]
[2119677480 2146527276 2117208971 1766903581 2146434055]
[1553428929 2108947358 1568126993 2118212065   86852210]
[1918248053 16

  0%|          | 467/217801 [00:03<26:16, 137.83it/s]

[1964869363 1584824651 1523925454 2123548791 1515577951]
[2892046258 2135008522 2080039599 2148421284 2083166693]
[2538318788 2055908685]
[2075808633 2124973130 2006344679 2024773026 1964105054]
[1542916279 2087262388]
[2095487435 2126163873 2143092196 1915196340 2161576649]
[2077367280 2146048155 2151802597 2168150254 2172018168]
[2074516465 2138542831 2159093920 2102865297 2165238559]
[1667182463    7549854 2036013482 2239684923 2576281169]
462
[2091092523 2482755436 1581407096 1495554662]
[2155689997   69565185  148764827 2144143407 2178742257]
[2152609355 2170909854 2141618784 1974120505 2097964935]
[2081160624 2552197822]
[1592960953 2120973478 1531623617 1513933745 1973108237]
[2149502453 1576195516 2089507474 2114028154 2023568310]
[2171511666 2117685088   19756977 2250296630 2139123334]
[2110679033 2010301509 1968762526 2077354880 2161019132]
470
[1979325497    1140107 2075310148 2139061136 1965473057]
471
[2058166223 2201646840 2096111026   86103893 1609222523]
[1821374449 216

  0%|          | 495/217801 [00:03<29:17, 123.67it/s]

[1898735459 2016714227 2011384915 2278988629 2324482072]
[1518240578  167151779 1515200814  160533777  597016695]
[2081053428 2020635076 2078508369  125328907 2090776985]
[2098115602 2144714216 1836118933  949520759 1791244351]
[1981885501 1990389445 1995446089 2562226322 1187830701]
[2040975483 2003123321 1998489325 2010145084 2122627722]
[2125225143 2122478169 2023273453 2162851162 2129793842]
[2048580947  102429762 2123564153 2101325662 2016166826]
[1515857575 1756240635 1975230264  156128023 2129292012]
[1832500336 2112543636 2169648163 2024980584 2532967650]
[2085610433 2005468169 2147646115  792635591 2110429142]
[1570307721 2085937120 2508512371 2081706699 1561709097]
[1632114991 2087165009 2611810350 1510854198  900993354]
[2122086266 2039760575 1987193942 2127217676 1803733812]
[2060141207 1588399981 2081833475 1857640830 2123642537]
[ 158559845 2167012317 2075151683 2572745851]
[1538296207 2154464520 2157017008 1606447110 2087809089]
[2136310957 1888392380 2021994557 24700070

  0%|          | 524/217801 [00:04<28:17, 127.98it/s]

[1977502354 2786305128 1489464626 1593853426 2027314791]
[2069372334 2082781794 2059025276 1999454387 1601124178]
[1987522618 1971471239 2516150684 2071879021 2521644033]
[2064347257  124644083 2059109080 2109583775 1828125472]
[2086071885 2146462352 2187556855 2272334239 1564337752]
[2064115172 1538316665 2012999037 1991573039 2148581625]
[2293806897 1515481093 2157355551 2408065462 1525621930]
[2031696998 2160537075 2118292600 2123272248 2160485598]
[1978577143 2023408138 2109145143 1567507049 2038772173]
[2020999234 2076118331 1997063559  186085407 2168962753]
[1997304099 2001028610 2168510574 2007921544 2063537687]
[2055676969 2112741343 2104719652 2118056561 2133413077]
[1975521395 2131757650 1871472387 1871472387 2149678969]
[1507749978 1582962837 1573293233 2032765975 2159532126]
[1607628562   81790750 2137928397 1585779225 2088166277]
[2170338669 2061742318 2150636142 1973492476 2129545557]
[1535927710 2166753552 2002752188 2128360034 2090287737]
[2111741689 2251650114 20666611

  0%|          | 550/217801 [00:04<28:24, 127.47it/s]

[2010739835 2104523419 2098810658 2114667096 2114574164]
[2123453946 2096558825 2014763157 2112631146 2100410990]
[2111863285 2105571579 2183421385 2112108083]
[2116123869 2057819109 2070121236 2125935312 2064044127]
[ 55094321  57819958 138424710   2252690 127161056]
535
[2026005856 1582074725 1531428106 2273800182 1581499200]
[2154710621 2154327223 2300997755 2141230399 2625211170]
[2017684569 2110110888 2084344697 2786744296   23492225]
[2071875260 1842983576 2035068605 2156553244 2132530661]
[2121696980 2030814361 2054207963 2227687951 2224491922]
[2070423530 2146827826 2102615348 2124158231 2129964913]
[2167994609 1586090198 2062256234 1601733264 2153113544]
[2011610400   98280286 2077272676 1600473624 2100975968]
[2067853332 2018079881 2106090053 1966689924 2545528998]
[2105704928  156713644 2130127729 2028790960  975994960]
[2275138388  986375651 2219038056 2201763054 2291284044]
[1976380557  142831712 1643401571 2040764025 2115923045]
547
[2134522095 1983915551 1998448657 23984

  0%|          | 576/217801 [00:04<28:38, 126.40it/s]

[2075693023 1981903647 2004505784 2493535170 2133305891]
[   9273873 1485516007 2024145045 1992904575 2096827683]
558
[2159761160 2756665233 1564244485 1504072947 1513007486]
[2165979968 2123107811  177984263 2102733276 1979015808]
560
[2059784683 1982425031 2035516519 2065101416 2511750140]
[  61752751 2128990608  218864581  205833887 2516846915]
[1974358662 2143116731 1999922493 1977725626 1986000859]
[2132287235 2057360896 2153080693 2080047591 2750841029]
564
[2027024431 2025571923   26448575   26448575 1981006581]
[2127707422 2019833509 2182237943 2280604321]
[2121816623 2083089270 2100866821 2310514039 2161035629]
[2102330473 1992461078 2054791254 2026723208  195985014]
[2214785250 2202182607 2050056972 2143811359 2075893214]
[2108454922 1508368570  178536341 2100759886 2251345433]
[2167863977 2169270531 2080741759   57492816 2133963889]
571
[2128402656 1492397400 2030690140 1500396425 2127125335]
[2102881299 2146828512 2132027883 2069667482 2145426052]
[2159306459 1990144545 150

  0%|          | 606/217801 [00:04<26:42, 135.52it/s]

[2140278783 2090769298 2054992386 2046145377 1538385713]
[2092615331 1975549749 1975549749 1975549749 2145339943]
[2007071800 2052648997 2034669636 1151269922 2188909969]
[1573118894 1888501279 2123593835  165221799]
[2150361105 1498054333 1522361664  179483649 2127717229]
[2345492474 1648555071 2258713440 2122774038 2396826172]
[1986340747 2118365168 2056390551 1976502522 2087767222]
[2108381092   85639745 2028908942 2114095746 1801334426]
[2600686309 1966723394 2760861319 2523125815 2734817039]
[2016048072 2104157999 2012364352 2767607256 2596274875]
[2052942525 2050019454 2138007263 2066305013 2136492099]
[2012190590 2080985074  176167878 2533080650 1647135165]
[1845739708 2240547236 2148326605 2227480894 1846656092]
[2008776938 1987113397 2057450058 1990470142 1824659232]
[2402811574 2017371989 2081560265]
[1770135642 1604864516 1564679070 1525464531 1508854386]
[1501833607 2031419217 2027479817  197400970 1537690804]
[1598302128  104481230 2133471522 2024583143 1526052277]
[200819

  0%|          | 634/217801 [00:04<27:27, 131.80it/s]

[2093516495 2092246018 2136095948  124636764  227333426]
[2159756799 2111020819 2126289012 2096753332 1980106054]
[1982690181 1559687211 1494897913 1582332154   78852118]
[2155310982 1983392241 2048538797 2054267955 2151137175]
[1538854182 2147726437 1517116503 2181594120]
[2134968647 2044584285 1992002269   97408691 1983777000]
[  53748369 2025221647 2115135048   44223722   30285657]
[2117735246 2148983548 2115831926 2161071431 2153909001]
[1833494600 1899513939 1543782760 1546910080 2267701652]
620
[2130281033 2115455197 2139129784 2169508341 2082543871]
[2065399045 2094704680 1951081122 2118302966 1984383968]
[1996982690 1985115527 2014712501 2085041321 1504742154]
[   5209863 1927820993 2461190640 2521483992 2007984567]
624
[2157083801 2151226386 1495557642 2114178685 2125940008]
[2132218677 2081666563  609503659  609503659 1966493488]
[1510710056 2022815033 2149406594 2166953159 2027981429]
[2130079918 1575800660 1504409053 1533547999 2004733860]
[2132014457 2132460690  113781070 

  0%|          | 662/217801 [00:05<27:23, 132.13it/s]

[2097847369 1583738858 2006246187 1964972981 2035291731]
[2024288382   90152184 2031963122]
[1743475680 2129348840 2141512618 2116378308 2118956317]
[2144123593 2141656264 2171831739 1964566177 2163164396]
[2034482176  153723057 1977656060 2164041216 2005871446]
642
[1608021225 1500066768 2108669032 1980425977 2611310061]
[2131359132 2132130537 2161496718 2117618926 2161523741]
[2165001600 2010362656]
[2115316459 2404416613 2396093498 2138090731 1838260653]
[2144127426 2066671721 2026678777 1486997620 2022545334]
[2563001386 2034600513 2142493985 2123400678 2580081096]
[1967310867 2072295764 2140929211 1962172852 2021434088]
[1832970435 1925895805 2025291840 2150914109  197153931]
[2097253200 2066754979 2030489943 2031447531 2084543877]
[2013451666 2188905909 2142634613 1992198088 2105047810]
[2284351912 1990443649 2091924280 2052739751 2037434835]
[2606738625 2496193619 2128609215 2128682443 2143089852]
[2150207495 2171453939 2108430095 2129783558 2155262538]
[2126053368 2111734174 21

  0%|          | 690/217801 [00:05<27:11, 133.05it/s]

[1963827069 2029307214 2131017271 2114668191 2154102696]
[2589484118 1984536882 2063817871 2014918341 2032839388]
[2164052363 1598759141 1509991416 2118131693 1789474086]
[2039887695 2018054118 2164213041 2171729263 2309257785]
[2119111481 2068959787 2128021408 2034076462 1991928089]
[2498525840 2094005170   82869071 1985325184 2103356780]
671
[2268428504 2278920123 2201173397 1604739405 2035530865]
[2486460265 1965159636 2109601832 2004634414 2165838660]
[2044123278 2037784149 2142857241 1986795400 1995826735]
[2116882280 2068146784 2170317108 1964012101 2106736633]
[1996901532 2153819533 2142578745 1978340904 2113980084]
[1985193734 2158400542 2177298128   88743612 2592605995]
[2029132652 2114304568 2024814006 2003161186 2012427958]
[2066322950 2134643511 1886381013 2281141369 1965316962]
[2071802423 1978277148 2734379643 1660488570 2751925665]
[2101533523 1984974851 1879422552 2153928296 2003341679]
[2164440793 2179714566 2072855519 1986170940 2033659894]
[2010569611 2751797913 1971

  0%|          | 719/217801 [00:05<26:23, 137.11it/s]

[2025553758 1534521585 1971748236 2143225137 2495948417]
[2050432237 2076662080 2054823966 1973991062  138962311]
[2147650421 2295622790 2118155805 2105315191 1959349287]
[2041908271 2052868552 2135258644 1975377830 1480900947]
[1852422273 2491798796 2293332382 2172099251 2588166047]
[1772464603  132013764]
[2127414233 1971864291 2342280918 2169036685 1557868286]
[2033233650 1979744784 2122883649 2039812439 2581557417]
[2135012291 1557828026  110997576 2180920399   15155850]
[2116604999 1504131871 2086625764 2157016246 2008149206]
[2036389305 1719993500 2037010846  126096422 1754613984]
[2036956884 2224826676 2402811379   45752121  142048424]
[1490859879 1491435788 2159882882 2167762629 2091755602]
[2065674789 2010916425 2010916425 2002337543 1528501518]
[1577643193 1996343284 2101522684 1570565962 1548088581]
[2113430875 1978010603 1549188177]
[205468804  91051643]
[2135498576 1769664091 2091092523 1862070398 2353017495]
[1976147587 2015110960 2108906655 2123798132 2153256137]
[205976

  0%|          | 733/217801 [00:05<28:45, 125.80it/s]

[2092994466 2126284795   85793560 2397642553 1563707167]
721
[2089809239 2045523265 2115387976 2398645097 2133479837]
[2120895415  216174336 2151392394 2130550547 1575488744]
723
[   6519013 1490929439 1860650736 1502432478 2020513678]
[2107096626 1997978901 2057851050 2594730095  182526625]
[2167281811 2017927822  194029977 2186999487 2466017630]
[2127083809 1541445224 2087159983 1601326754 2098772804]
[1858222367 1576316852 2126970319  149198795   93878129]
[2107823104   97190690 1979376659 1993962570  239165158]
729
[1503599674 1968622343 2172031602 2115057505 1579921674]
[1535417994 2148687996 2013681472 2044568771 2015901765]
[2132281952 2077190826 1579406746 2136065509  156145416]
[2146693432 1524894467 2135017848 2118737060 2015674745]
[1504204077 2115548327]
[1573426382 2131770667  186281313 1522740415 2029791960]
[2045035063 2148037317 1530286501]
[2398164674  138276892   37497580 2407179788 2029814172]
737
[1782590233 2001785244 2107558380  182571476 1644641054]
[2011985314 2

  0%|          | 759/217801 [00:05<29:53, 120.99it/s]

[2128541179 2126864248 2020186952 2148641603 2126108707]
[2096532105 2079079970 2007547643 1566388542 1526198568]
[2096962027 2110645462 2044615599  858357416 2076236672]
746
[  49804672 1583878596 2200626381 2104689585]
747
[2118025528 2118836531 2124600577 2147885303 2136391815]
[2164870960 2153784889 2132080280 2121965361 1981240833]
[1608419391  123319811 2101360396   41744863 2408198315]
[2005069458 2038343373 2045566047 2055800023 1921929190]
[2160134714  170865367 2095124761 2086337177 1971204556]
[2007254584 2036995325 2466716394  396877415 2192823225]
[  79832321 2135143344   31244569 1888975701 2621712891]
[2084847520 2148591238 2791154369 2121266258 1568243475]
[2003516014 1984205382 2474068088 2784771879 2103485484]
[2128350470 2148792001 2033325312 1875108425 2095832706]
757
[2109033710 2119600129 2126475077 2036083077 1605432049]
[2089160254 1973291434 2144780749 1549164528 2079127545]
[2153118028 1980567021 2163969089 1992005334 2147452548]
[1970462831 2150491652 1533198

  0%|          | 785/217801 [00:06<30:00, 120.50it/s]

[2027028300 2086446064 1549012662 2033663024 2149201427]
[ 146461994 1506358826 2094169824  130852049  189284911]
[1636072027 2048089658 1497964292 2566455629 1568000525]
[2133099404 1995012079 2062824198 2061912355 2010888763]
[2088294379 1483180434 2205241371 1587317768 2285566927]
[2013430312 2136408619 2293933899 2753364850  132201200]
[2058618078 2052132642 2130770194 2238502235 2151084071]
[2293997542 2591264712 2404375817 2142532986 2400297987]
[2044560939 2048051309 2143232039 2020169768 2110123236]
[2069853034 2127275895   94306613  182994832  181365381]
[2050138027 2119058595 1998729616 2259762438 2154032543]
[2035500672 2138015656 2034765131 2165077131 2089558423]
778
[1976248891 2101706889 2023979681 2035120105 2055242664]
[2139019659 2159269870 2043174713 1966395229 1970255480]
[2141128179 2069571482 2150631474 2498935687 2152338072]
[2058768373 2170321340  760246721 1492757440]
[2095435811 2741261446 1987789460 1802782715  155519550]
[2153529655 2033280977 1494700845 2114

  0%|          | 812/217801 [00:06<28:45, 125.73it/s]

[2618563266 2048384241 2053640619 1552338675 2625477426]
[1517665537 2394595052 2296229554 1513646797 2256443950]
[2140089060 2578954904 2394925871 2613434883  799624518]
[2034920586 2050344571 2286617883 2272899048 2730848592]
[2097162292 2125808184 2140103399 2004314225 2131493224]
[ 198410213  841229804 2312918109 1529197466 1543895059]
[2147137699 2096663388 1974506110 2137262291 2520129492]
[2028904519 2004214228 1987425720 2073023209 2015525779]
[1821142549 1882784061 2042118400 1980851624   19135382]
801
[ 316763119 1517771839 1992454046 1748393397 2109802560]
[2090325367 2400857455 2032771859 2051493734 2294375985]
[2135577965 2106388306 2138861322 2060314659   19815571]
[2002653563  118489722 1487616311   93101529  207460437]
[2117885077 1975627161 2106904049 1996380539 1629434878]
[2119035727 1966820659 2124137467 2114461832 2114596304]
[2080157231 2106488983 2082750454 2145717442 1965076526]
[2035809865 1557239654 1844442355 2079531926 2153191296]
[1479700734 2151478921 2129

  0%|          | 839/217801 [00:06<28:08, 128.51it/s]

[  96361426 1586253720 2304062524 2004673438 2249587194]
[2162422574 2092858671 1583799338 2162778607 2138365299]
[1597807146 2141291477 2033019659 2113049725 1587874771]
[2039223248 2045250915 2291739878  124001196 2898913030]
[1981777422 2095519876 2077749854 2092409890  384797372]
[2147743629 2170241157 1628605343 2075285664 1608475339]
[2122994248 1579772076 2126718757 1986566755 2395488179]
[2027494374 1980030575 2062587841 2074730180 1582765807]
[2066007148 2085104977 2609294769]
[1548969407 1990086710 1987401411 2235976952 2133163398]
[2165069655 1978430408 2783147858 1482815748 2016980626]
[1964439412 1504834688  181213310  152587550 1519415801]
831
[1580684460 1560826078 2079138654 1527426340 1549990851]
[1913314108 2117624199 2153982906 2081438358 2113971243]
[1979636842 1540016664 2073051573 1516817778  183463200]
[2088508682 2083904045  187498582 2128123914 1808076984]
[1480878783 1522439499 2029867601 2147395854 2709115149]
[1975524609 1979903077 2063155285 2088216027 1505

  0%|          | 865/217801 [00:06<29:36, 122.10it/s]

[2102391253 1991418450 2092401580 2038705170 2100423948]
[2056291622 2379117798 2044152878 2169231276 2003303518]
[2163289463 2143395586 2080211619 2098571599 2044928927]
[1969709265 1969709265 2137999759 2146538435 2146538435]
[2752885492 1507039213  105768903 2752600339 1497470190]
[1783988560 2103776060 2016469379 1963504939 2181837723]
[1995935241 2062973095 2125083169 2548627465  623714281]
[2156653782 2027622024 2056642787 2049846847 2013979607]
[2741058991 1825781359  565101429 2145536095 2774000165]
[2148645123 2106386304 2071981034  272510176]
855
[2139567006 1916443078 1484700541 2100841731 2125841638]
[2087661061 1571439140 2621105131 2604200129 2058220696]
[ 173768667 2406180397   86851296 2037257380  361622972]
858
[2137744223 2047149517 2142821364 2597920441   53831618]
[2111372556 2492534616 1999969035 2532761731 2107371728]
[2080672717 1982509364  180102709 2131207830 2050437513]
[1519135310 2281063491 1530234341 1543075479 2270154306]
[2034920586 2050344571 2270061820 

  0%|          | 891/217801 [00:06<30:44, 117.58it/s]

[2138536735 2141833837 2145570862 1794195530 2099295806]
[2019589186  126070631 2185289172 2506091136]
[ 308849112 1995002252 2098624096 2157865314 2051530898]
[1584008964 1537714433 2535462744 2296402327 1973623217]
[2001575223 1983416666 2099409750 2075354524 2144191864]
[1499412453 2075843426 2100375232  148513544 1538444406]
[2102036064 2108417568   32342861 1851022341   95992764]
[1972119307  174741263 2122153992 2071929645]
[1898251192 2022364797 1500872918 2102134785  347583059]
[1974084458 2140654465 2109545181 2119723190 1577057697]
[ 132739645 2052642746 2114500314 2505852838 2082857672]
[2115396357 2020814075 2022135434 2027396162  150886561]
[1628605343 2075285664 1964847500 2130842379 2077997907]
[2100935296 1554694181 2006204710 2072882373 2053501423]
884
[2026263244  176998357 1977799087 1981773538 1557369306]
[1565623053 2148506544 2052653988 2024522546 2148149459]
[1513612157 1482851941 2016513432 1516724173 2097510099]
[2468337398 2613715541 1973735378 2121153597 1494

  0%|          | 915/217801 [00:07<32:13, 112.20it/s]

894
[2146344029 2028638596 2171731083 2095911686   19399476]
[2098814788 1579997106 1586692687 2264016962 2073781647]
[1911131648 2099560701 1923988726 2299395700 1802184568]
897
[2101234009 2044105167 2151591509 2151591509 1728842521]
[2143276519 2663233842 2034141636 2133388964 2060821576]
[1806068651 2114964867 1922719437 2287833784 2396384305]
[2073499905 1993734353 2113566137 2165069655 2276457769]
[2142772413 2009932683   81869639 2551212478]
[2102600871 2102600871 2106239882 2106239882 1943306457]
[2204717410  189592349  202248108 2259305363   21549134]
904
[1926961671 2104258060 1935530605 2295409577  935434364]
[1999396723 2161358581 2171108507 2015896257 2150240056]
[2320034101 1995852445 2089589794 1983610905 2090505208]
[  12892115    2483745 2082170226 2046714731 1982038565]
908
[1625113512 1028003223 2506112859 1555596782 1617252280]
[2115801316 2147311167 1965141016 1978215768 2161998322]
[2021962600 1997650479 1565221498 2083478423 2096576843]
[2098832077 1983514445 206

  0%|          | 944/217801 [00:07<28:01, 128.99it/s]

[1945443124 2613833277 2753588254 2043472121 2185208441]
[2048433053 1595392398 1524938675 1522956798  128175867]
[2130373340    3845198 2038764711   44377596 2204734806]
918
[2022166150 2114544510 2619697128 2122465162 2100408869]
[1490647514 1537992138 2101796636   44806593 2139214794]
[2171392343 2271328583 2040714324 1575987759 2116210991]
[1987878450 2053096658  192438917 2094982051 2038654169]
[1583295953 2106192381 1586167239 2888504590 2504260463]
[2252072953 2119876468 1586135067 2250853956 2105201713]
[2100807107 2170907756 2050175553 2118878957 2121271591]
[2104759957 2068646921 2103185925 1815830542 2165819508]
[2042626986 2033385642 2293974431 2046337761 2211809397]
[2057664528 2165823172 2023916559 1979364456 2131952030]
[1527766738 1965850056 2010023761 2294314598 1907276435]
[1980425590 1562899493  114887881 1994207125  148383226]
[1525243411  181306761 1510871247 2110332835 2097680906]
[1992474904 2092250841 2098577709 2059319469 1965273172]
[2004933787 2049582887 2069

  0%|          | 958/217801 [00:07<28:40, 126.01it/s]

[1608773992 2127816745   66184116 2141195113 2017332349]
946
[2167088175   73085516 2115890165]
[2136443568 2116133514 2394108223 2070442000 2125411686]
[1666112599 1980277249]
[2005161317 2017584927 2101140105 2314281595 2754191581]
[1974376973 1996918480 2043829315 1566933724 2067528161]
[2056650049 2169879540 1968586006 2037133027 2119888718]
[1846385217  104136890 1512322889 2074818257   25977876]
953
[2094568767 1976371754 2128551894 2169868363   12540587]
954
[1992399362 2120648263 2000618564 1969074628  158445715]
[2114841454 1977689296 2163904859 2071867975 2176476431]
[   8550301 2165496929 2728059831  339896394 2765383698]
957
[1597212252 2738403630 2623769373   87337125 1544002944]
958
[2050668158 2276264695 1547405997 2086179895 2025157342]
[2115406066 1991353505 2041605806 1972932886 1591520422]
[2170415662 2067734263 1487021523 1962239380 2101526016]
961
[1500151097 2495014966 2245202549 2255362520 2119137688]
[2068986213 1877952707 1970851236 2045453701 2238220152]
[2027

  0%|          | 985/217801 [00:07<29:15, 123.48it/s]

[1994181344 2089507241 2118744608 2035871140 1547131737]
[2003834374 2067691799 2317531084 1662473291 1545494143]
[2153794097 2153794097 1904607992 2039192691 2103862049]
[2116610673 1988827736 2023104914  603995401 2048525266]
[1488771041 1523992493 1989974095 2043369301 2059425849]
[2161118867 2110205132 2153353823 1904505074 2166644802]
[2098218790  175409452  195670248 2397914681  916723664]
[2129975319 1503845337  118378145   73578444 2488820423]
[2053696585 2023699349 2162870648 2047183410 2152372327]
[1988156201 1537772377 2501310531  153684471 2002958129]
[2063230375 2064508306 2076267738 2055516810 2122415453]
[2762689525 1967138980 2143677012 2046697132 2171738417]
[2111000201 2141027246 1645679354 2137854238 2038935070]
[1977638826 1496981308 2146482510 1975372675 2014107750]
[2142350809 2142350809 2134203307 2131484543 2127400668]
[2408277762   39510776 2165512325 1978366466 1582115593]
984
[2161067131 1996249351 2161967451 2156496641 1987692705]
[1503708149 2142414945 2135

  0%|          | 1011/217801 [00:07<28:50, 125.31it/s]

995
[1974779377 1568205223 2221972625 1496338221 1577655622]
[2402434285 1511645536 2165904303]
[1995008440 2047927383 2109577449 2139971047 2055368483]
[1823801573 2268016259 2269312071 2408222857 2243490828]
[2070183171   30044362 2134141465 2243242557  131811946]
1000
[2284435198 1542706181 1555829539 2131740062 2149582425]
[2025631880 2202376658 2039712832 2126180566 1545357982]
[2044120541 2116445679 2108961243 2138220291 2153448130]
[ 962940480 2273836721 2146639726 2080162560 2867890001]
1004
[1964778859  123302925 2168583459 2766168180 2472794676]
[1841214913 1861939714 2167974157 2119679246 1487332506]
[1603192282 1528976180 2113960410 1570438586 2120870923]
[2020189063 2033215896 2098423036 2098951456 2013432403]
[2095590927 2142763962 2138232185 1681480812 2096708189]
[2026032877 2043582729 1493512125 1724869758 2046649680]
[2760664922    2193149 2278242120 2283578529 2130313331]
1011
[1969456244 2107454866 2107454866 2041580402 2120004185]
[1968444938 2036144085 2011257065 

  0%|          | 1039/217801 [00:08<27:23, 131.88it/s]

[1540324141 2171633114   78496157 1938016043 1627121531]
[2122235358 1513431614  114077326 2133636077 1486631742]
[2792371739 1989688706 2098344853 1585290860 1505593098]
[2294529060 1561267720  559974119 2293645068 2017552311]
[1482095069 2136926847 2083310421 1588254135 2048132113]
[2127489984 2121504382 2158245987 1983526026 2617392052]
[2143665444 2060059186 1973494824 2203412431 2116964414]
[2155626861 1499217709 1558331296 2188152545   81674092]
[2106019599 2307804823 2148892780 1963671699 1828824667]
[ 174290064 1623815286 1977977500 2240881863   32164771]
1031
[1507676740   34112310 2900995323]
[1767990287 2074001172 2117593603 1991999918 2145020764]
[2158992420 2059444492 2030541823 2009041676 2102757197]
[2125806346 1992843940 1819955114 2163886161 2068639971]
[2121115269 2146570985 2000111599 2159439794 2115501161]
[2001089796 2165934314 2532847441 2085956717 2014181096]
[2163065828 1570763516 2045500667 1898681721 2156899428]
[1991334006    8913454 2009379862 2506353248 203

  0%|          | 1068/217801 [00:08<26:39, 135.46it/s]

[2110642088 2116596942 2161985854 2108937378 2011679994]
[2046778872 1868621362 2166446824 2036676638 2131910367]
[2139660542 2057312398 2161564750 2158058396 1965664017]
[2162903974 2515060514 2058028893 2026207448 2547987305]
[2170530433 1608888274 2041204355 2045516750 1980473534]
[1968075755 2156844454 2155899557 2017605317 2066634361]
[1984584030 2110994387 1985823812]
[2145522924 2017217780 1982107955 2014850133 2113283805]
[2049451506 1549012806   66118639 1537471652 1523201337]
[1526502205 1975290712 2109076275 1637173820 2064685859]
[2139450036 2805889152 2116512888 1485750786 2132130797]
[2172071721 2079339284 2068671681   50843133 2567829267]
[1990308949 2001150693 1591465506  120113773]
[2116716880 2086925983 2080018172 2127893664 1990387805]
[2144638120 2186701992 2158056182  203145905  158053417]
[2088339987 1880942083 1963664254 2094082306 2030761477]
[2013434113 1608781114 2337968673 1802483710 2254042067]
[2117829666 2006187024 2596254416 1967370444 1825391200]
[208097

  1%|          | 1096/217801 [00:08<26:44, 135.04it/s]

[2108430911  114518124]
[2019553156 2253521306 2467688258 2163331102  206040426]
[2121451934 2128765420 2081131254 2151546482 2215849660]
[1980461259 2141837166 1997820657 2042873748 2030123043]
[2093107137  117587020 1548392653]
[2078753712 2015801922 2070995723 2101152687 2152194316]
[2142517505 2062896923 2019919653  105827035 1600414501]
[1997062118 1963849940 2132832707  656566143  659384654]
[2038177382 2051268134 2148772545 2130607897 2051737747]
[2001882260  106502512 2016111824 2747381720 1982513619]
1088
[2079854797 2172064476 2095825766 2119653453 2118497654]
[1996964465 2201547006 1685042191 2466258525]
[2294395356 2073742357 1975808766 1976978933 1436965661]
[2566053671 2075149513 1550815238 2143470045 2003117117]
[2096356985 2032551902 2079493184 2144596760 2036534296]
[2008553165 2001979729 2061292696 2141864406   37964093]
[2006786297 2160635326 1994001307 2098747075 2135300620]
[2128257312 2052464005  195870166 2281254702 1589100336]
[1923938124 2324889505 2425900105 2

  1%|          | 1124/217801 [00:08<28:46, 125.47it/s]

[2104752900 1556556941 2613312629 1593569365   48953020]
1105
[1526726828 1543031826 2544745230 1471542436 2144137480]
[2015198215 2212626793 2496451142 2533334511 2531262574]
[2118420859  822568613]
[2022447133 2091642668 1823196464 2129588091 2158242231]
[1975470983 1991651582 2021609618 1817545098 2088290231]
[2164337732 2039025009 2027590524 2030427965   70242218]
[ 158990785 1484603919 2066521614 2031662677 2172267799]
[  31632659  151325408  134028907 2400208831 1536026156]
1113
[2096659092 1521122940 2130238741 1508632717 1525754303]
[2041127769 2165760757 2121359722 2063361568 2077456416]
[1695032500 2132724442  191348530 2134884076 2169989606]
[2160183719 2049009664 2285827435 2004851214 2043395275]
1117
[2053585705 2056605643 2565054113 2551240332 2023138889]
[2134168908 2766182427 1544319520 2561995736 2019340895]
[2095488795 2095488795 2018273263 2009211454 2009211454]
[2348936988 2349902723   62137368 2623792720  323145296]
1121
[1489161917 2079426237 2318675602 1807631646

  1%|          | 1150/217801 [00:08<30:12, 119.51it/s]

[1877351922  948168507 2883837465 2043935153 2782689775]
[1945787009 1545904712 1999762264 2771882211]
[2146466672 2045221772 1904452829 2010682628 1711499209]
[1964241047 1989147187 2035709231 1987684126 2133572815]
[2285666196 1848655804 2129386480 1848608616   23200061]
[2104998382 2106970252 2109466626 2130344021 1569541426]
[1990491187 2143453411 2068007459 1987202809 1972443998]
[2129496494 2019664122 1562773508 1712469354 1569284626]
[2095518456  143555546 1599825994 1963756232 2156921267]
[2015782999 1997045529 1481907038 1975679561 2128096972]
[2047228628 2167247989 1820815218 1845379656 2047389942]
[2170571644 2624445461 2082492347 2341445124 1537846377]
[2052655467 2153707499 2055420047]
[2044184930 2137893669 2136016236 2167563176 2010803799]
[1985327120 1985327120 2111783629 1976623182 2170702893]
[2592636588 1991124442 2735421631 2735545549 2734045776]
[  44611163 2062130831  192167603 2268996352  163019065]
1143
[  32882897 2528280489 2330499168  646652464 2058647021]
[2

  1%|          | 1163/217801 [00:09<30:37, 117.90it/s]

[1511688816 2138612658 1879281873 2503657378 2125651818]
[1598234692 2399669637  293532674 2168299138 2133848669]
[1607089216 2090551264 2100205350 1589729740 2126198163]
[1591736534 2323257625 1748440566 1990237550 1922146726]
[2157908076 1908422888 2223674019 2109391865 1596295676]
[2067012475 1992124283 2045663419 2164039975 2103277171]
[1548148540 1804110266 2025800439 2114482313 2160932744]
[  60369657 1993193917 2396116703 1984961803 2404134020]
[2164295484 2275116544 1820145464 2299022738 1921533404]
1160
[1984484432  344902574 1987634687 1985139715 2731713178]
[2168915676 1772955114 1859915253 2153852017 2303443042]
[1483253792 1533463762 2284050418 2594143608 2707781218]
[2134064894 1751494390  128131994 2167876098 1555358873]
[1571615440 2111141292 2136033258 1660714679 2055947235]
[2026926213 1985896931 2079641762   80957921 2794756405]
[2107647422 2117846201 2119967662 2040823429 2153115882]
[1995854116 2181827775 2017215980 2394821019  131149777]
[2126250402 2120574524 250

  1%|          | 1191/217801 [00:09<28:22, 127.22it/s]

[2114265471 2115056368 2125387246 2162716252 1968510170]
[2074814670 1566590895 1502628442 2074988668 1675187506]
[2569065106 2081765322 2223317490 2542679102]
[2156237322 2515053095 2147384103 2556064866 2040682501]
[2070205520  187209110 2602949383 2233819697 2478465355]
[2134883135 2067582164 2004335077 2168175076 2139065753]
[1665472765 2400929237  268724411 2617210971 2400061226]
[2120398992 2053798192 2075608792 2067812894 1555744841]
[2091576221 2000075560 2130401083 1978920103 2053615203]
[2163642647   76826465 2106740217 2068021035 2162810918]
[2167949584 2094042081 2261921216 2619834248 2778442578]
[1567570992 2142378923 2136903747 2120614617 2151702936]
[1547089199 2300656643 1527045081 1491393253 1582902762]
[2093412843 2031879787  143821170 2111344184 2108918451]
[2139734816 2138012559 2022987374 1846353404 1567876833]
[2083058050 2112792171 2085666071 2094459054 2055560990]
[2141762210 1878216034]
[2049497032 2053034494 2250662150 2039305231 1484282256]
[2140919237 212729

  1%|          | 1217/217801 [00:09<28:30, 126.59it/s]

[2115226770 2108077335 1494626233 2152501153  322948363]
[1979991500 2135530488 2017009364 1980767556 2256693363]
[2004463884 2130724591 1514580951 2057073240 2049916782]
[2053729169 1520598104 2112048547 2137548912 2096444256]
[1759463127 1911958278 2160838543 1657706103 1889873938]
[1988241516 2028899194 2574253606 2396478789 1507243310]
[1978235861 2149167609 1967310439 1967310439 2136404418]
[2035041833 1963591592 2121672959 2165766008 2106367955]
[2112170521 1974564856 2167146754  962414901 1883704353]
[2104182459 2105853795 1899483886 1923038941 2106263738]
[2008576646 2101930193 2571056751 2171170678]
[2042701657 2134789439 2019445713 2142142817 2100279146]
[2612591813 2058580347 1990944369 2115611540 2207691166]
[2089150756 2079421249 2136507825 2131193678 2144080413]
[2127617483 2151574744 1486986145 2044146440 1540792544]
[2003238113 2164810125 2078250442 2167797188 2041440979]
[2028503167 2113657649 1689901425 1013290596 1998889070]
[2141374566 1578929447 2067161439   995249

  1%|          | 1245/217801 [00:09<27:42, 130.29it/s]

[2255909464 1546715194 1547706610 1707815481 2400364513]
[2095073910 2112505974 1847535063 2160504298 1994408974]
[2477666898 2018390989 1971928443 2065548758 2007195729]
[2149236835 2141988289 2124430419 2112867573 2148994573]
[1981992757 1989166442 2131850986   42450573 2070293423]
[2053272364 2037770017 1589389886 1604351666 2012925426]
[1490312738 2012955245 2511844115 1995068038 2159404386]
[1585814348 2053528567 1244374401 2068912397   84158582]
[2049953405 1509551972 2611176548 1988446106 2051735096]
[2106277773 2120750550 2138118304 2122102310 2210322478]
[2096945214 2044527070 2145271904 2011050576 2127398547]
[2140119286 2068345402 2003835812 2091963994]
[1583529081 1499361794]
[2097195619 1977358285]
[1505698820 2100755359 1477456140  124828701   42231441]
[1579780413 2122948053 2141421119 2768121635 2732623801]
[1994391783 2090882370 2152759852 2116114398 2133908773]
[2003553553  198059962 2023900889 2155721937 2204285055]
[2057778465 2160898872 1977171554 2089215627 209113

  1%|          | 1272/217801 [00:09<27:59, 128.96it/s]

[2118324373 2170269213 2159814723 2091550212 1488506636]
[2151448598 2567204772 2347145335 1650103138 1968841965]
[2006703870 1898798377 2170122347 2113243825 2046791129]
[2112227057 1980850818 2048157132 2251280415 2152913516]
[2007755560 2295465721 2467074172 2293249015 2052816682]
[2407232104  153320552 2042028307 2171947673 2238222460]
[1992868980 2153431772 2027718081 1996137482 2065385897]
[2136514583 2104878392 2012896813 2000941677 2113443914]
[1933146504 1772923315 2007680337 2293781712 2062242702]
[2021498796 1707170858 1518341281 2183291554 2106830587]
[1657123160 2160533691  170018322  170018322 2290636264]
[2052104835 2046246518 2107838985 1970967634 2158110558]
[2008847126 2002958129 1541361613 2013547172 2045488547]
[2026617585 2045063849 1558281341 2156615572 2098671757]
[2120892287 2329582599 2406544394 2400954971 1990688801]
[2081939415 2124088405 2027937844 2073800390 2081547332]
[2163122879 2109633310 2154840865 2135077150 1895529909]
[2107589078 2142638723   347328

  1%|          | 1299/217801 [00:10<27:54, 129.30it/s]

[2169327824 2183463966 1965790416 1887296892  140690265]
[2085925396 2181457088 2090961276 2394570054 2015985273]
[1492460849 2033656559 2011455705  186629949 1501777548]
[ 173956503 2160732112 1152166452   80719611  322824424]
[2109111030 1989163463 2149653219 2126409412 1497335207]
[2092382025 1986632472 2156286319 2013391098 1905525776]
[1540921462 2127050759 1984220200 2032138925 2045787977]
[2089310204 2023485678 2054333807 2020045709 2060403661]
[2100169223 2160760990 2095801673 2140698087 2117208220]
[2038585482 1488378957 1595133024   82661287 2042672602]
[1608845133 2127591200 1519686635  774058779 1489927383]
[1984016160 2057348139]
[2163886442 2041351581 2161931647 2063790512 2048641976]
[2072445657 1510354412 2157752164 2129982676 2113540078]
[   9292421 2000775387 2438911840 2295760257 2146357154]
1297
[1992050139 1502365580 1533825398 1507521263   78642047]
[2128266483 2251992196 2250666668 2561096068 2183460629]
[2063147917 2091453914 2121840840]
[2133998224 2341210013 1

  1%|          | 1327/217801 [00:10<27:43, 130.10it/s]

[2086002527 2804997759 1993199145 2240243392 2227709137]
[2055075080 2308071406 2117072511  232820894 2121382102]
[2095099252 1999489024 2021070905 2013497789 1534694639]
1313
[2014596857 2037941060 2077655735 2052822586 1978386138]
[2147120293 2078250521 2053343137]
[2130789586   50227226   26718485  186966335 1617566164]
[2096985690 2158830496 2135597114 1999994039 1986183106]
[1976775924 1539170234 1565021725  647878058 1522225311]
[1995487919 1980875809 1785249454  108349602 2591711548]
[2161012989 2141954481 2155416230  122252244 2071837210]
[1591833645  203633640 2296743260 2573351398 2511641841]
[2037820911 2037820911 2338172851 2028168301 2142113614]
[2006750207 1889461403 2405536428 2328176792  845997863]
[2164679086 2560410072 2086621068 2088423856 2294505721]
[2168378416 2167213403 2059897574 1553941020  102741441]
[2152342394  160911278  196152232 2022180804 2108782267]
[1572430894 1996938536]
[2143109153 1776498962 1994609277 1993239831 1603466863]
[2125241523    6503115  

  1%|          | 1354/217801 [00:10<28:08, 128.19it/s]

[2167188088  115970217 2106898383 1833803359 2404900368]
[2077319860 2156247678 2088420375 2079800633 2078079928]
[2152441241  105661677 1982430640 2400075161 1509857015]
[2166301347 1535569416 2026941724 1985565667  153753654]
[2031247812 2130640375 2049935875 1986764497 2276235818]
[2098561412 2037608562 1993259333 2031406010   71789194]
[1988828484 1536679637 2023726332  196816329]
[1971532690 1551553517 2026255285 2029762370 2078484001]
[2099789029 2105381522 1976237736 2097615184 2105818150]
[2146580156 1533901057 1544757802 2092159918 2257570500]
[1990566849 2137347187 2027541194 2065923787 1995169133]
[2037395587 2160842479 2016307857 2092331212 2068864418]
[2012959900 1517464903 1983160424 1983421263 2163595220]
[2109138290 2064990378 1906989660 2540285784 2117206772]
[2096980612 2046456909 2139068239 2005303773 2011919809]
[2003626473 2076618284 2065365067 1596596196 2105159196]
[2101005742 2162337786 2030724586 2100250898 1970275213]
[2123716411 2161499268  127699494]
[216273

  1%|          | 1380/217801 [00:10<29:39, 121.65it/s]

[1964166152 1542685742 2069256165 1977187942 2019744552]
[2114557229 2038890262 2211425607 1584796481  348505267]
[2076291573 1546993153 2157177828  175554243 2034684123]
[ 118884931 2132429870   67721698 2152509033 2154439137]
[2055140198 1985335492 2110865920 2163267301 2480837897]
1366
[2054064936 2160668718    7696661 2487280803 2079188094]
1367
[2160625611 2160625611 1989437487 1991300616 2005202728]
[2211558534   83783524 2012213904 1507567055 1606538849]
[1983547737 1540540181 2028004422 1629553608 2032475218]
[ 102708294 2201552871 2113970290 2152293830 2294548604]
[ 830659737 1613386253 1585214758 2110237340 1485388873]
[1987469388 2045263759 2140950877 2124014126 2024395588]
[2113677269 2114307208 1561981064 2094358804 1984567898]
[2022564930 1565457373 1863049369 2144962576   83409048]
1375
[2094108185 2024384475 2148097581 2082306822 2014215091]
[2144381298 2827966998 2140299094  210040110 2604365969]
[2142082251 2040179055 2126793736   80054432 2049603565]
[1952332000 1991

  1%|          | 1407/217801 [00:11<29:00, 124.34it/s]

[1579049907 2244083715 1522994958 1594536462 1580769899]
[2098449997 2032507921 2109813080 2094788431 2142784426]
[2146095405 2124320287 2086144884 2044306109 2055510968]
[1645021839 2052124310 1574516252 2022749141  122954271]
[1574681435 1033787497 2409357721 1568294368 1585418846]
[ 181507321 2510462315  172839780 1480191585 2161547988]
[2489225573  159547535 2064005706 2508631855 2169593029]
[2066633870 2337558443 1992316446   59467864 1987011436]
1392
[2035850477 2044977944 2121598047 1445605299  162238120]
[2130724591 1573210599 2167084044 2304832331 2136029563]
[2153465044 2146346972 2108780087 2007824828  198367286]
[2105514582 1514361308 2068101455 1515357878 2792527638]
[2141931308 1931463589  226134553 1778865519 2140687800]
[1804888644 2124439852 2161969976 2131958595 2611875969]
[1550614927 2161558926 2054120547 2149417407 1517798700]
[2185497811 1967073859 1607018412 2016706173 2559987397]
[1505885302  114967581 2007247913 1894339932  123062047]
[1777573857 1812716701 180

  1%|          | 1421/217801 [00:11<28:14, 127.70it/s]

[1974719543 2118817344 2098975839 2148958130 2129088316]
[2164674456 2137070670 2106142943 1998871470 2142444070]
[2132967511 2119209999 1528515814]
[2012869797 1524911570 2022805940 2075937957 2162437555]
[2479975364 2485074437 2115409852 2061321794 2123359309]
[1991056282 2146237557 2129687578 2165339408 1969137703]
[2030700013 1965573334 2023733790 2081251812 2094112598]
[1990832096 2103817093 2103877122 1997147891 2135682468]
[1984272814 1884998714 1497215244   67557030  158455561]
[2000576071 2247697177 1535143292 1515658647 1836481518]


KeyboardInterrupt: 

In [82]:
np.sum(num==2029513180)

0

In [79]:
print(num.dtype)

int64


In [105]:
M = np.load('../data/N.npy')
print(M.shape)

(217801, 201)


In [106]:
M = M!=0
M = M.sum(axis=1)
M = M>0
print(M.shape)

(217801,)


In [94]:
print(np.sum(M))
print(len(M))
print(np.sum(M)/len(M))

12649
217801
0.05807595006450843


In [68]:
print(len(num))
print(N.shape[0])

624181
217801


In [63]:
import pandas as pd

In [33]:
# dataset creation
df_train = pd.read_csv('../data/train.csv', dtype={'author': np.int64, 'hindex': np.float32})
n_train = df_train.shape[0]
labels = np.zeros(n_train)
for i in tqdm(range(n_train)):
    if np.sum(df_train['author']==nodes[i]) == 0:
        continue
    labels[i] = df_train[df_train['author']==nodes[i]]['hindex']
print(labels)
print(np.sum(labels>0))
np.save('../data/labels.npy', labels)

  4%|▍         | 6589/174241 [00:04<02:03, 1361.61it/s]


KeyboardInterrupt: 

In [34]:
labels = np.load('../data/labels.npy')
print(len(labels))

174241


In [35]:
# read test data
df_test = pd.read_csv('../data/test.csv', dtype={'author': np.int64})
n_test = df_test.shape[0]
print(df_test)

       Unnamed: 0      author  hindex
0               0   915630815     NaN
1               1  1236455448     NaN
2               2  2694593333     NaN
3               3  2137926699     NaN
4               4  2883694285     NaN
...           ...         ...     ...
43555       43555  2145559725     NaN
43556       43556  2168342616     NaN
43557       43557  2162797290     NaN
43558       43558   294576894     NaN
43559       43559  2508925065     NaN

[43560 rows x 3 columns]


In [112]:
cfg = GNNWrapper.Config()
cfg.use_cuda = True
cfg.device = torch_gnn.utils.prepare_device(n_gpu_use=1, gpu_id=0)
cfg.tensorboard = False
cfg.epochs = 500

cfg.activation = nn.Tanh()
cfg.state_transition_hidden_dims = [5,]
cfg.output_function_hidden_dims = [5]
cfg.state_dim = 5
cfg.max_iterations = 50
cfg.convergence_threshold = 0.01
cfg.graph_based = False
cfg.log_interval = 10
cfg.task_type = "semisupervised"
cfg.lrw = 0.001

Executing on device:  cpu


In [113]:
Ed = []
for i in tqdm(range(E.shape[0])):
    if E[i,0] < 50 and E[i,1] < 50:
        Ed.append(E[i,:])
Ed = np.array(Ed)
#print(Ed)

100%|██████████| 1718164/1718164 [00:00<00:00, 1864428.82it/s]


In [114]:
print(Ed.shape)

(211, 3)


In [115]:
# model creation
model = GNNWrapper(cfg)

dset = torch_gnn.dataloader.from_EN_to_GNN(Ed, N[:50], targets=labels[:50], aggregation_type="sum", sparse_matrix=True)  # generate the dataset

model(dset)  # dataset initalization into the GNN

In [111]:
# training code
for epoch in tqdm(range(1, cfg.epochs + 1)):
    model.train_step(epoch)

    if epoch % 10 == 0:
        model.test_step(epoch)

  0%|          | 0/500 [00:00<?, ?it/s]


RuntimeError: shape '[1, 1, 67]' is invalid for input of size 50